[general]
import = [
    "~/.config/alacritty/themes/rose-pine.toml",
]

[font]
normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode Nerd Font"

size = 15.0
offset = { x = 0, y = 2 }

[cursor]
style = { shape = "Block", blinking= "Always" }
vi_mode_style = { shape = "Block", blinking= "On" }

[window]
padding = { x = 8, y = 16 }

[mouse]
hide_when_typing = true
